### ISSUE TITLE
Add noexport tag to some covers

### ISSUE THREAD

**Issue by nirbhasa** [vasudevaserver/sri-chinmoy-book-covers#1]
For example:

in jpg folder mfs could be renamed mfs-noexport
other covers: aaty_1 (but this is not a public book yet)

These would allow these to not be displayed publicly

**Comment by priyadarshan** [comment]
If I may partecipate in this discussion, I am personally hesitant to attach a semantic meaning to filenames, ie. appending a function to more of what they really are.

I know that we are doing this for some parts of the Archives as well, but that must really change that too, as it is, in my really humble opinion, an "unhealthy" choice in the long range, leading to confusion and blind alleys.

It is only my opinion, though. I would like to talk about it a little over the Pujaloy Event this Saturday, at least with Dharmik, if possible at all.

**Comment by nirbhasa** [comment]
OK, i will leave out manually
